### PR TITLE
docs(31_erc20): update doc

### PR DESCRIPTION
**Pull request by XdpCs**
## What type of PR is this

- [x] Typo
- [ ] BUG
- [ ] Improvement
- [ ] Feature

## Which issue(s) this PR fixes(Optional)

* resolve : #657 

## What this PR does / why we need it

fix md's warnings and update some errors.

### CODE REVIEW

**Comment by XdpCs** [comment]
* plz close : #657

**Comment by AmazingAng** [comment]
为什么要把external改成public?

**Comment by XdpCs** [comment]
eip-20标准中是 public, openzeppelin 实现的也是使用public
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol, https://eips.ethereum.org/EIPS/eip-20

**Comment by XdpCs** [comment]
> 为什么要把external改成public?

eip-20标准中是 public, openzeppelin 实现的也是使用public
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol, https://eips.ethereum.org/EIPS/eip-20

**Comment by AmazingAng** [comment]
好的

**Pull request merged**
