### PR TITLE
Fix keccak256(abi.encodePacked(addr, index)) => keccak256(abi.encode(…

### PR DESCRIPTION
**Pull request by LingYe-WEB3**
…addr, index))

### What type of PR is this (这是什么类型的PR)

- [✅ ] Typo(勘误)
- [ ] BUG(程序错误)
- [ ] Improvement(提升)
- [ ] Feature(新特性)

### Which issue(s) this PR fixes(Optional) (这个PR 修复了什么问题 (可选择))

* resolve(修复) : #

### What this PR does / why we need it (这个PR 做了什么/ 我们为什么需要这个PR)
在solidity的mapping计算插槽位置的计算方式错误，由abi.encodePacked更新为abi.encode

### CODE REVIEW

**Comment by XdpCs** [comment]
能提供你的参考资料
最好是Solidity官方的文档

**Comment by XdpCs** [comment]
> The value corresponding to a mapping key k is located at keccak256(h(k) . p) where . is concatenation and h is a function that is applied to the key depending on its type:
> 
> * for value types, h pads the value to 32 bytes in the same way as when storing the value in memory.
> * for strings and byte arrays, h(k) is just the unpadded data.
> 
> ref: https://docs.soliditylang.org/en/v0.8.28/internals/layout_in_storage.html

可能需要把这个重新整理一下 进入教程

**Comment by LingYe-WEB3** [comment]
> > The value corresponding to a mapping key k is located at keccak256(h(k) . p) where . is concatenation and h is a function that is applied to the key depending on its type:
> > 
> > * for value types, h pads the value to 32 bytes in the same way as when storing the value in memory.
> > * for strings and byte arrays, h(k) is just the unpadded data.
> > 
> > ref: https://docs.soliditylang.org/en/v0.8.28/internals/layout_in_storage.html
> 
> 可能需要把这个重新整理一下 进入教程

好的，那我更新一下这个分支，把这些信息写入教程。

**Review by LingYe-WEB3 — COMMENTED** [review]
"Update the method for reading the storage location of mappings."

**Comment by LingYe-WEB3** [comment]
@XdpCs 我根据Solidity官方的文档更新了mapping数据存储位置的计算方式。希望能够教程有所帮助。

**Comment by LingYe-WEB3** [comment]
> @XdpCs 我根据Solidity官方的文档更新了mapping数据存储位置的计算方式。希望能够教程有所帮助。

ref: https://docs.soliditylang.org/en/v0.8.28/internals/layout_in_storage.html

**Pull request merged**
