### PR TITLE
WTF Solidity Japanese mainly 101 Lesson 12 to 14

### PR DESCRIPTION
**Pull request by PolymetisOutis**
### What type of PR is this (这是什么类型的PR)

- [ ] Typo(勘误)
- [ ] BUG(程序错误)
- [x] Improvement(提升)
- [x] Feature(新特性)

### Which issue(s) this PR fixes(Optional) (这个PR 修复了什么问题 (可选择))

* resolve(修复) : #

### CODE REVIEW

**Comment by PolymetisOutis** [comment]
@AmazingAng CC: @thurendous 
Lesson 12~14 repo's push and personal recheck & modification has been done.

**Comment by thurendous** [comment]
これはPR被ってたら、クローズデ良いと思うが、どう？
@PolymetisOutis

**Comment by PolymetisOutis** [comment]
@thurendous CC* @AmazingAng 
ごもっとも。分けてPRしたんだけど、よく分かっていなかったから、クローズするよ！
Right. I made separate PRs, but because I didn't fully understand, I will close this PR!!

**Comment by PolymetisOutis** [comment]
@AmazingAng CC: @thurendous 
For following thurendous' comment and point, I tend to close this PR.

**Pull request closed without merging**
